### ISSUE TITLE
Question Editor window in Lessons is too big

### ISSUE THREAD

**Issue by ilyankou** [ram8647/gcb-clone-v111#11]
Fix CSS

**Comment by ilyankou** [comment]
Go to:
`->` Google Course Builder Dashboard
`--->` Style
`----->` CSS
`------->` assets/css/main.css

scroll all the way to the bottom and add:
```css
#modal-editor-iframe {
  max-height: 90vh !important;
  margin-top: -45vh !important;
}
```

This will position question editor iframes on top, and they will never exceed the height of 90% of the screen (with margins of 5% on top and 5% at the bottom). If the iframe is too big, scrolling enables. The downside of it is that smaller windows will not be positioned in the center of the screen, but will always be in the upper half.

I think this `css` file is considered course content, right? (Because when I do local changes and deploy them, the css file does not get updated).

@ram8647
