### ISSUE TITLE
Change cursor view to "pointer" for .gcb-button

### ISSUE THREAD

**Issue by ilyankou** [ram8647/gcb-clone-v111#18]
In Dashboard, go to Style > CSS > main.css, find the style for `.gcb-button` and add the last line:

```css
.gcb-button {
  .......
  cursor: pointer;
}
```
