### ISSUE TITLE
Get rid of horizontal scrolling in Teacher dashboard

### ISSUE THREAD

**Issue by ilyankou** [ram8647/gcb-clone-v111#19]
In both Chrome and Safari, there is horizontal scrolling in Teacher dashboard and not in other tabs.

![screen shot 2017-06-30 at 18 55 57](https://user-images.githubusercontent.com/10443203/27756538-7788dea0-5dc6-11e7-99b8-9c071672fcd3.png)

**Comment by ilyankou** [comment]
Solved and changes are pushed.

Added this rule to `teacher.css`:
```css
html {
  width: calc(100% - 30px) !important;
}
```
